services:
  db:
    image: postgres:18-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d CleanArchDb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-core_api
    ports:
      - "5169:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Overriding appsettings.json
      - ConnectionStrings__DbConnectionString=Host=db;Port=5432;Database=${DB_DATABASE};Username=${DB_USER};Password=${DB_PASSWORD}
      - SmtpSettings__Host=${SMTP_HOST}
      - SmtpSettings__Port=${SMTP_PORT}
      - SmtpSettings__Email=${SMTP_EMAIL}
      - SmtpSettings__From=${SMTP_FROM}
      - SmtpSettings__Username=${SMTP_USERNAME}
      - SmtpSettings__Password=${SMTP_PASSWORD}
      - SmtpSettings__UseSsl=${SMTP_SSL}
      - SmtpSettings__IsAuthenticated=${SMTP_USE_AUTHENTICATION}
      - S3Settings__AccessKey=${S3_ACCESS_KEY}
      - S3Settings__SecretKey=${S3_SECRET_KEY}
      - S3Settings__URL=${S3_URL}
      - S3Settings__Bucket=${S3_BUCKET}
      - JwtOptions__Secret=${JWT_SECRET}
      - Admin__Username=${ADMIN_USERNAME}
      - Admin__Email=${ADMIN_EMAIL}
      - Admin__Password=${ADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: